import Link from 'next/link';
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: Readonly<{
    children: React.ReactNode;
  }>) => {
    return (
        <div className={`${geistSans.variable} ${geistMono.variable} antialiased min-w-fit lg:min-w-0 lg:max-w-5xl lg:mx-auto`}>
            <nav>
                <ul>
                    <li>
                        <Link href="/">Home</Link>
                    </li>
                    <li>
                        <Link href="/about">About</Link>
                    </li>
                </ul>
            </nav>
            <main class='h-100'>{children}</main> 
            <footer className="footer">Ormait.com.br</footer>
        </div>
    );
};

export default Layout;